<?xml version="1.0" encoding="utf-8"?><Database Name="ventas" Class="ServicioLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=PC-DAVID\SQLEXPRESS;Initial Catalog=ventas;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ventasConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.empresa" Member="empresa">
    <Type Name="empresa">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="identificacion" Type="System.String" DbType="NChar(12)" CanBeNull="true" />
      <Column Name="razonSocial" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="NChar(12)" CanBeNull="true" />
      <Column Name="correoContacto" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="represemtanteLegal" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.persona" Member="persona">
    <Type Name="persona">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="documento" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="edad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>